encoding: utf-8

# seo
title: Scott.WDR'Blog
description: Scott.WDR'Blog
keywords: Blog,Scott.WDR'Blog
author: Scott.WDR

# "","/blog"
context: ""
scheme: "http"
domain: "blog.tmaize.net"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2016
beianhao: "皖ICP备xxxx号"

coderay:
  coderay_tab_width: 4

# Gitalk
gitalk: 
  enable: true    #用来做启用判断可以不用
  clientID: '86de3a763db76425e2f6'    #上面生成的往这里怼
  clientSecret: '4dab7e678cd58693a4116d356aca0a0dd80c060b'   #同上
  repo: a807966224.github.io    #仓库名称
  owner: 807966224@qq.com    #github用户名
  admin: Scott.WDR
  distractionFreeMode: true