encoding: utf-8

# seo
title: Scott.WDR'Blog
description: Scott.WDR'Blog
keywords: Blog,Scott.WDR'Blog
author: Scott.WDR

# "","/blog"
context: ""
scheme: "https"
domain: "a807966224.github.io"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2016
beianhao: "皖ICP备xxxx号"

coderay:
  coderay_tab_width: 4